services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - 50000:50000
    labels:
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.steffbeckers-tutoring-devops-playground.localhost`)"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
  jenkins-agent-1:
    image: jenkins/inbound-agent:latest-jdk17
    container_name: jenkins-agent-1
    restart: always
    environment:
      - JENKINS_URL=http://jenkins.steffbeckers-tutoring-devops-playground.localhost
      - JENKINS_AGENT_NAME=agent-1
      - JENKINS_SECRET=e5b39d326fc0f2dd5684be0734c3bd8aafbcd7e923a7bc817b2293568b8074d4
