services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    labels:
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.steffbeckers-tutoring-devops-playground.localhost`)"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
