services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - 5000
    labels:
      - "traefik.http.routers.registry.rule=Host(`registry.steffbeckers-tutoring-devops-playground.localhost`)"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"
