name: steffbeckers-tutoring-devops-playground

services:
  angular:
    image: ghcr.io/steffbeckers-tutoring/devops-playground-angular
    container_name: angular
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../../apps/angular
    labels:
      - "traefik.http.routers.angular.rule=Host(`angular.steffbeckers-tutoring-devops-playground.localhost`)"
      - "traefik.http.services.angular.loadbalancer.server.port=4000"
      - "traefik.http.routers.angular-api.rule=Host(`angular.steffbeckers-tutoring-devops-playground.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.angular-api.entrypoints=web" # Use web entry point
      - "traefik.http.routers.angular-api.service=dotnet"
